// Code generated by extract.py. DO NOT EDIT.

package export

const (
	TCGETS = 3
	TCSETS = 0
	IGNBRK = 0x0004
	BRKINT = 0x0001
	PARMRK = 0x0400
	ISTRIP = 0x0080
	INLCR  = 0x0020
	IGNCR  = 0x0008
	ICRNL  = 0x0002
	IXON   = 0x0200
	OPOST  = 0x0001
	ECHO   = 0x00000008
	ECHONL = 0x00000001
	ICANON = 0x0010
	ISIG   = 0x0040
	IEXTEN = 0x0020
	CSIZE  = 0x0030
	PARENB = 0x0200
	CS8    = 0x0030
	VMIN   = 6
	VTIME  = 10
)

type Termios struct {
	Cflag uint32
	Iflag uint32
	Lflag uint32
	Oflag uint32
	Cc    [11]uint8
}
