// Code generated by extract.py. DO NOT EDIT.

package export

const (
	IGNBRK = 0x1
	BRKINT = 0x2
	PARMRK = 0x8
	ISTRIP = 0x20
	INLCR  = 0x40
	IGNCR  = 0x80
	ICRNL  = 0x100
	OPOST  = 0x1
	ECHO   = 0x8
)
