// Code generated by extract.py. DO NOT EDIT.

package export

const (
	TCGETS = 0x5401
	TCSETS = 0x5402
	IGNBRK = 0x1
	BRKINT = 0x2
	PARMRK = 0x8
	ISTRIP = 0x20
	INLCR  = 0x40
	IGNCR  = 0x80
	ICRNL  = 0x100
	IXON   = 0x200
	OPOST  = 0x1
	ECHO   = 0x8
	ECHONL = 0x40
	ICANON = 0x2
	ISIG   = 0x1
	IEXTEN = 0x200000
	CSIZE  = 0x30
	PARENB = 0x100
	CS8    = 0x30
	VMIN   = 0x4
	VTIME  = 0x5
)

type Termios struct {
	Iflag uint32
	Oflag uint32
	Cflag uint32
	Lflag uint32
	Cc    [16]uint8
}
